### ISSUE TITLE
Ability to make a test on virtual device where mobilepay is not installed

### ISSUE THREAD

**Issue by welrachid** [MobilePayDev/MobilePay-AppSwitch-SDK#1]
Hi guys.
Can you provide a small snippet of code that can help simulate the "callback" that comes from mobile pay app for testing on virtual devices? specifically on ios.
I'm working on a phonegap app

sorry if this is the wrong place. Couldnt find any other place to post a question

Thanks

**Comment by PelleRavn** [comment]
@welrachid When ever I test on e.g. the Simulator, I skip the MobilePay flow completely and only test my own logic.
Lets say I press a "Pay with MobilePay" button, I then check if MobilePay is installed, and if it isn't I'll call that method that finished the order (who normally would be called by the MobilePay callback) with the "OrderID" and "Amount" I passed to the AppSwitch SDK. For the "TransactionID" I'll reference to what they specify for the [ServerURL callback](https://github.com/MobilePayDev/MobilePay-AppSwitch-SDK/wiki/Getting-started-on-iPhone#4-handle-callbacks-from-mobilepay).

It's pointless to try and simulate the "OpenUrl"-AppDelegate, and it might even fail since you haven't setup the SDK on the Simulator.

Hope it was what you were looking for.

**Comment by welrachid** [comment]
unfortunately im not deep in the ios dev code, so im not sure how everything else works.. i was just thinking that maybe someone had a codesnippet that is something like this
if(running in simulator){ make the callback-simulation with transaction id 12345678901234567890}
else{ usual stuff} (including checking if MP is installed etc.}

**Comment by PelleRavn** [comment]
I'm not really into how Phonegap integrates the AppSwitch SDK, so can't help you there.
But my small "guide" should be the way to test the flow on virtual devices, if you manage to figure out how the iOS integration with Phonegap works :)

**Comment by lmktrifork** [comment]
@welrachid Hopefully the advice that @PelleRavn has provided you with, gave you the help you needed. if not please try here: https://github.com/mrlund/cordova-mobilepay-appswitch. This is a plugin which someone else has made. Perhaps they can help you. However as we do not provide official support for cross-platforms such as phonegap, we will close this issue.
