### ISSUE TITLE
Error  with code 1001 

### ISSUE THREAD

**Issue by OyaSaid** [MobilePayDev/MobilePay-AppSwitch-SDK#2]
Hello I get the following error when I start to open the MobilePay application. The MobilePay app opens but the error is still received:

`Error Domain=com.danskebank.mobilepay Code=1001 "Not able to open an app which responds to the urlScheme" UserInfo={NSLocalizedRecoverySuggestion=This should be setup under UrlIdentifier in your info.plist, NSLocalizedDescription=Not able to open an app which responds to the urlScheme, NSLocalizedFailureReason=This app do not respond to the given urlscheme 'AppName'}`

And I have added the url scheme
![screen shot 2017-01-17 at 1 23 08 pm](https://cloud.githubusercontent.com/assets/3874256/22020399/56276018-dcb8-11e6-8e5f-18973b5ee6ff.png)

Also I have in my App Delegate the following code
 [[MobilePayManager sharedInstance] setupWithMerchantId:MOBILEPAY_MERCHANT_ID merchantUrlScheme:[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleDisplayName"]  country:MobilePayCountry_Norway];

Can you please tell me why do I get the error if I have added everything

**Comment by lmktrifork** [comment]
Which version of the SDK are you using?
Which merchant id are you using? the test id "APPNO0000000000" or your production id? is it a string?
It is not recommended to use the app's name directly as the URL scheme as it may contain special characters or change at some point. This should be a static string - much like the Facebook URL scheme. 
Try setting both parameters as strings as per the example code in order to isolate the error.
https://github.com/MobilePayDev/MobilePay-AppSwitch-SDK/blob/master/src/examples/MobilePayFruitshop-iPhone/MobilePayFruitshop/AppDelegate.m

**Comment by OyaSaid** [comment]
Hello, It worked if I use pure strings instead of $(PRODUCT_NAME)
Thanks

**Comment by lmktrifork** [comment]
Good to hear that your issue was resolved.
