### ISSUE TITLE
Possible to get bitcode enabled?

### ISSUE THREAD

**Issue by xthedeus** [MobilePayDev/MobilePay-AppSwitch-SDK#3]
Hello, I need to have bitcode enabled for my project but when I try to build the project I get the following error:

```
MobilePayManager/libMobilePayManager1.8.0.a(bio_lib.o)' does not contain bitcode. You must
rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from
the vendor, or disable bitcode for this target. for architecture arm64
```

Is it possible that you add bitcode to the library?

**Comment by lmktrifork** [comment]
A part of the SDK is OpenSSL library and that library does not have support for bitcode, and because of this, it is not possible for us to enable bitcode in the SDK currently. If the OpenSSL SDK for iOS gets official support for bitcode then we add this asap.
Currently it is not a requirement to have bitcode enabled in your project, so you can safely disable bitcode.
