### ISSUE TITLE
Bitcode is not enabled for MobilePay-AppSwitch-SDK

### ISSUE THREAD

**Issue by mihirpmehta** [MobilePayDev/MobilePay-AppSwitch-SDK#5]
Bit code is not enabled for this library. due to which Apps that uses this SDK, couldn't use powerful feature of bitcode for the app.

**Comment by lmktrifork** [comment]
A part of the SDK is OpenSSL library and that library does not have support for bitcode, and because of this, it is not possible for us to enable bitcode in the SDK currently. If the OpenSSL SDK for iOS gets official support for bitcode then we add this asap.
Currently it is not a requirement to have bitcode enabled in your project.
